config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    resources :patients
    resources :diagnoses
    resources :doctors
    resources :static_pages

    root 'static_pages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/diagnose.rb
class Diagnose < ActiveRecord::Base
belongs_to :patient
end

app/models/diagnosis.rb
class Diagnosis < ActiveRecord::Base

end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
    
end

app/models/patient.rb
class Patient < ActiveRecord::Base
has_many :diagnoses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/diagnoses_controller.rb
class DiagnosesController < ApplicationController
    def index
        @diagnosis = Diagnose.all
    end

    def show
        @diagnosi = Diagnose.find(params[:id])
    end

    def new
       @diagnosi = Diagnose.new
    end

    def create
            @diagnosi = Diagnose.new(diagnosis_params)
                if @diagnosi.save
                    redirect_to @diagnosi
                  else
                    redirect_to diagnoses_path
                  end

    end

    def destroy
        @diagnoses = Diagnose.find(params[:id]).destroy
        flash[:success] = "Diagnóstico Eliminado."
        redirect_to @diagnoses
    end

    private

    def diagnosis_params
            params.require(:diagnose).permit(:diagnosis, :description)
    end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
    def index
        @doctors = Doctor.all
    end
    
    def show
        @doctors = Doctor.find(params[:id])
    end
    
    def new
       @doctors = Doctor.new 
    end
    
    def create
        @doctors = Doctor.new(post_params)
            if @doctors.save
                redirect_to @doctors
            else
                render :new
            end
    end
    
    def destroy
        @doctors = Doctor.find(params[:id]).destroy
            flash[:success] = "Medico Eliminado."
            redirect_to @doctors
    end
        
    private
        
    def post_params
            params.require(:doctor).permit(:name, :specialty, :cmdv)
    end    
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
	def index
		@patients = Patient.all
	end

	def show
		@patient = Patient.find(params[:id])
	end

	def new
		@patient = Patient.new
		@diagnosis=Diagnosis.all
	end

	def create
            @patients = Patient.new(patient_params)
                if @patients.save
                    redirect_to @patients, notice:"El paciente se agrego a la base de datos exitosamente."
                else
                    render :new
                end
    end
		def edit
     @patient = Patient.find(params[:id])
		end

		def update

			@patient=Patient.find(params[:id]).update(patient_params)
				  flash[:success] = "Diagnóstico Eliminado."
					redirect_to patients_url
			end

    def destroy
        @patients = Diagnosis.find(params[:id]).destroy
        flash[:success] = "Diagnóstico Eliminado."
        redirect_to @patients
    end

        private

    def patient_params
        params.require(:patient).permit(:firstname, :middlename, :lastname, :address, :birth_date)
    end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    def index
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/diagnoses_helper.rb
module DiagnosesHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/diagnoses/index.html.erb
<%= stylesheet_link_tag "application" %>

<h1>Lista de Diagnósticos Médicos</h1>

<p>La siguiente es una lista de diagnosticos medicos previamente agregadas por los doctores.</p>
<p>Por favor sea bastante claro en la lista de diagnosticos para los demas usuarios.</p>

<table>
    <thead>
        <tr>
            <th>Diagnóstico Clínico</th>
            <th>Descripcion</th>
        </tr>
    </thead>
    <tbody>
        <% @diagnosis.each do |diagnosis| %>
            <tr>
                <td><%= diagnosis.diagnosis %></td>
                <td><%= diagnosis.description%></td>
                <td><%= link_to 'Eliminar Diagnostico', diagnoses, method: :delete, data: { confirm: 'Esta Seguro de eliminar el Diagnóstico? Perdera la información previamente ingresada.' } %></td>
            </tr>
        <% end %>
    </tbody>
</table>
<br/>
<%= link_to 'Nuevo Diagnostico', new_diagnosis_path %>
<br/>
<br/>
<%= link_to 'Volver', static_pages_path %>

app/views/diagnoses/new.html.erb
<%= form_for(@diagnosi) do |f| %>

    <p>
        <strong>Diagnostico</strong><br/>
        <%= f.text_field :diagnosis %>
    </p>

    <p>
        <strong>Direccion</strong><br/>
        <%= f.text_area :description, size: "60x20" %>
    </p>

    <%= f.submit "Agregar Diagnóstico a la lista" %>

<% end %>

app/views/diagnoses/show.html.erb
<h1> Diagnostico Ingresado </h1>
        <p>
            <strong>Id del Diagnostico </strong>
            <%= @diagnoses.id %>
        </p>

        <p>
            <strong>Diagnóstico Médico</strong>
            <%= @diagnoses.diagnosis %>
        </p>
    
        <p>
            <strong>Descripción del diagnóstico</strong>
            <%= @diagnoses.description %>
        </p>

        <%= link_to 'Volver a lista de diagnósticos', diagnoses_path %>

app/views/doctors/index.html.erb
<%= stylesheet_link_tag "application" %>

<h1>Doctores en Línea</h1>

<p>A continuación se le presenta una lista de doctores registrados en sistema</p>
<p>En caso de no ver su nombre disponible por favor solicite registrarse o hagalo ud mismo por la opcion Agregar Doctor</p>

<table>
    <thead>
        <tr>
            <th>Nombre del Doctor</th>
            <th>Especialidad</th>
            <th>Codigo del Colegio de Medicos de Venezuela</th>
        </tr>
    </thead> 
    <tbody>
        <% @doctors.each do |doctor| %>
            <tr>
                <td><%= doctor.name %></td>
                <td><%= doctor.specialty%></td>
                <td><center><%= doctor.cmdv%></center></td>
                <td><%= link_to 'Eliminar Doctor Registrado', doctor, method: :delete, data: { confirm: 'Esta Seguro de eliminar el registro del doctor? Perdera la información previamente ingresada.' } %></td>
            </tr>
        <% end %>
    </tbody>
</table>
<br/>
<%= link_to 'Agregar Doctor', new_doctor_path %>
<br/>
<br/>
<%= link_to 'Volver', static_pages_path %>

app/views/doctors/new.html.erb
<%= form_for(@doctors) do |f| %>

    <p>
        <strong>Nombre</strong><br/>
        <%= f.text_field :name %>
    </p>

    <p>
        <strong>Especialidad</strong><br/>
        <%= f.text_field :specialty %>
    </p>

    <p>
        <strong>Codigo del Colegio de Medicos de Venezuela</strong><br/>
        <%= f.text_field :cmdv %>
    </p>

    <%= f.submit "Agregar Doctor al registro" %>

<% end %>

app/views/doctors/show.html.erb
<h1> Datos del paciente </h1>
        <p>
            <strong>Id del Doctor </strong>
            <%= @doctors.id %>
        </p>

        <p>
            <strong>Nombre del Doctor</strong>
            <%= @doctors.name %>
        </p>
    
        <p>
            <strong>Especialidad</strong>
            <%= @doctors.specialty %>
        </p>

        <p>
            <strong>Codigo del Colegio de Medicos de Venezuela</strong>
            <%= @doctors.cmdv %>
        </p>

        <%= link_to 'Volver a lista de doctores', doctors_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MedRecs</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/patients/edit.html.erb
<%= form_for(@patient) do |f| %>

    <p>
        <strong>Primer Nombre</strong><br/>
        <%= f.text_field :firstname %>
    </p>

    <p>
        <strong>Segundo Nombre</strong><br/>
        <%= f.text_field :middlename %>
    </p>

    <p>
        <strong>Apellidos</strong><br/>
        <%= f.text_field :lastname %>
    </p>

    <p>
        <strong>Direccion</strong><br/>
        <%= f.text_area :address, size: "40x2" %>
    </p>

    <p>
        <strong>Fecha de nacimiento</strong><br/>
        <%= f.date_select :birth_date, {order: [:day,:month,:year], start_year: 1900} %>
    </p>

    <%= f.submit "Agregar Paciente" %>

<% end %>

app/views/patients/index.html.erb
<%= stylesheet_link_tag "application" %>

<h1> LISTA DE PACIENTES </h1>

<table border="1" border-style="solid">
	<thead>
		<tr>
            <th>Id. del Paciente</th>
			<th>Primer Nombre</th>
			<th>Segundo Nombre</th>
			<th>Apellidos</th>
			<th>Dirección</th>
			<th>Fecha de Nacimiento</th>
		</tr>
	</thead>

	<tbody>
		<% @patients.each do |patient| %>
			<tr>
                <td><%= patient.id %></td>
				<td><%= patient.firstname %></td>
				<td><%= patient.middlename %></td>
				<td><%= patient.lastname %></td>
				<td><%= patient.address %></td>
				<td><%= patient.birth_date.strftime("%d/%m/%Y") %></td>
        <td><%= link_to 'Mostrar Paciente', patient %></td>
				<td><%= link_to 'editar',edit_patient_path(patient) %></td>
				<td><%= link_to 'Eliminar Paciente', patient, method: :delete, data: { confirm: 'Esta Seguro de eliminar el paciente?' } %></td>
			</tr>d
		<% end %>
	</tbody>
</table>
<br/>
<%= link_to 'Nuevo Paciente', new_patient_path %>
<br/>
<br/>
<%= link_to 'Volver', static_pages_path %>

app/views/patients/new.html.erb
<%= form_for(@patients) do |f| %>

    <p>
        <strong>Primer Nombre</strong><br/>
        <%= f.text_field :firstname %>
    </p>

    <p>
        <strong>Segundo Nombre</strong><br/>
        <%= f.text_field :middlename %>
    </p>

    <p>
        <strong>Apellidos</strong><br/>
        <%= f.text_field :lastname %>
    </p>

    <p>
        <strong>Direccion</strong><br/>
        <%= f.text_area :address, size: "40x2" %>
    </p>
        
    <p>
        <strong>Fecha de nacimiento</strong><br/>
        <%= f.date_select :birth_date, {order: [:day,:month,:year], start_year: 1900} %>
    </p>    

    <%= f.submit "Agregar Paciente" %>

<% end %>

app/views/patients/show.html.erb
<h1> Datos del paciente </h1>
        <p>
            <strong># Paciente </strong>
            <%= @patient.id %>
        </p>

        <p>
            <strong>Primer Nombre</strong>
            <%= @patient.firstname %>
        </p>

        <p>
            <strong>Segundo Nombre</strong>
            <%= @patient.middlename %>
        </p>

        <p>
            <strong>Apellidos</strong>
            <%= @patient.lastname %>      
        </p>

        <p>
            <strong>Direccion</strong>
            <%= @patient.address %>
        </p>

        <p>
            <strong>Fecha de Nacimiento</strong>
            <%= @patient.birth_date.strftime("%d/%m/%Y") %>
        </p>

        <%= link_to 'Volver a Pacientes', patients_path %>

app/views/static_pages/index.html.erb
<%= stylesheet_link_tag "application" %>

<h1>Bienvenidos al sistema de Historias Medicas</h1>

<h4>Menú de opciones</h4>

<p>A continuacion se le presenta un menú de opciones para el medico, elija una.</p>

<p>
    <%= link_to 'Pacientes', patients_path %>
</p>

<p>
    <%= link_to 'Diagnósticos', diagnoses_path %>
</p>

<p>
    <%= link_to 'Doctores', doctors_path %>
</p>